configs:
 userName: root
 password: public
 jdbcUrl: jdbc:postgresql://192.168.6.15:5432/actorcloud
 tableName: device_events
 columns:
  - topic
  - msgTime
  - tenantID
  - productID
  - deviceID
  - data
  - dataType
  - streamID
  - responseResult
