postgres:
  postgres_host: 127.0.0.1
  postgres_port: 5432
  postgres_user: root
  postgres_password: public
  postgres_database: actorcloud

emqx:
  emqx_app_id: actorcloud
  emqx_app_secret: 2U9UbsAJcTtweu7e0GXY
  emqx_lb_ip: 127.0.0.1  # cluster LB ip. if there is no cluster, it is emqx node ip
  emqx_api_port: 8080  # emqx http api port, the default is 8080
  emqx_nodes:
    - 192.168.1.2  # emqx node1 internal ip
    - 192.168.1.3  # emqx node2 internal ip

mail:
  mail_server: 'smtp.163.com'  # smtp server
  mail_port: '25'  # smtp server port
  mail_use_ssl: False  # whether to use ssl
  mail_username: 'emqtest@163.com'  # email username
  mail_password: 'emqtest1713'  # email password
  mail_default_sender: 'emqtest@163.com'  # default sender

actorcloud:
  log_level: error
  log_path: /opt/tmp/logs
  backend_node: 0.0.0.0:7000  # backend server ip:port
  task_scheduler_node: 0.0.0.0:7001  # task scheduler node
  timezone: Asia/Shanghai
  secret_key: sfsdfsdfsdfasd0241243d##!@$@$@$j
  admin_email: admin@emqx.io  # super administrator login username
  admin_password: public  # super administrator login password
  site_name: ActorCloud  # the site name
  site_domain: console.actorcloud.io  # the site site domain
  email_title: ActorCloud registration invitation # invitation registration email title
  default_devices_limit: 100  # number of devices that tenant can manage. no limit is -1
