# dict code yml

# Base
serviceGroup:
  - code: serviceGroup
    codeValue: 1
    enLabel: Base
    zhLabel: 基础服务
  - code: serviceGroup
    codeValue: 2
    enLabel: DMP
    zhLabel: 设备管理平台 DMP
  - code: serviceGroup
    codeValue: 3
    enLabel: AEP
    zhLabel: 应用使能平台 AEP
  - code: serviceGroup
    codeValue: 4
    enLabel: Value-Added
    zhLabel: 增值服务
msgType:
  - code: msgType
    codeValue: 1
    enLabel: login
    zhLabel: 登录
  - code: msgType
    codeValue: 2
    enLabel: subscribe
    zhLabel: 订阅
  - code: msgType
    codeValue: 3
    enLabel: unsubscribe
    zhLabel: 取消订阅
  - code: msgType
    codeValue: 4
    enLabel: publish
    zhLabel: 发布
  - code: msgType
    codeValue: 5
    enLabel: receive
    zhLabel: 接收消息


# User
tenantType:
  - code: tenantType
    codeValue: 1
    enLabel: Individual User
    zhLabel: 个人用户
  - code: tenantType
    codeValue: 2
    enLabel: Business User
    zhLabel: 企业用户
userAuthType:
  - code: userAuthType
    codeValue: 1
    enLabel: Role
    zhLabel: 角色
  - code: userAuthType
    codeValue: 2
    enLabel: Role and Group
    zhLabel: 角色和分组
inviteStatus:
  - code: inviteStatus
    codeValue: 0
    enLabel: Not Joined
    zhLabel: 未加入
  - code: inviteStatus
    codeValue: 1
    enLabel: Joined
    zhLabel: 已加入
isLogged:
  - code: isLogged
    codeValue: 0
    enLabel: Failed
    zhLabel: 失败
  - code: isLogged
    codeValue: 1
    enLabel: Success
    zhLabel: 成功


# Device
deviceStatus:
  - code: deviceStatus
    codeValue: 0
    enLabel: Offline
    zhLabel: 离线
  - code: deviceStatus
    codeValue: 1
    enLabel: Online
    zhLabel: 在线
  - code: deviceStatus
    codeValue: 2
    enLabel: Sleep
    zhLabel: 休眠
authType:
  - code: authType
    codeValue: 1
    enLabel: Token
    zhLabel: Token
  - code: authType
    codeValue: 2
    enLabel: Certificate
    zhLabel: 证书
upLinkSystem:
  - code: upLinkSystem
    codeValue: 1
    enLabel: Cloud
    zhLabel: 云
  - code: upLinkSystem
    codeValue: 2
    enLabel: Device
    zhLabel: 设备
  - code: upLinkSystem
    codeValue: 3
    enLabel: Gateway
    zhLabel: 网关
connectStatus:
  - code: connectStatus
    codeValue: 0
    enLabel: Offline
    zhLabel: 下线
  - code: connectStatus
    codeValue: 1
    enLabel: Online
    zhLabel: 上线
  - code: connectStatus
    codeValue: 2
    enLabel: Authenticate Failed
    zhLabel: 认证失败
deviceBlocked:
  - code: deviceBlocked
    codeValue: 0
    enLabel: Allowed
    zhLabel: 允许访问
  - code: deviceBlocked
    codeValue: 1
    enLabel: Not Allowed
    zhLabel: 不允许访问
enable:
  - code: enable
    codeValue: 1
    enLabel: Enable
    zhLabel: 允许
  - code: enable
    codeValue: 0
    enLabel: Disable
    zhLabel: 不允许
certEnable:
  - code: certEnable
    codeValue: 1
    enLabel: Enable
    zhLabel: 可用
  - code: certEnable
    codeValue: 0
    enLabel: Disable
    zhLabel: 不可用
sdkType:
  - code: sdkType
    codeValue: 1
    enLabel: Application
    zhLabel: 应用程序
  - code: sdkType
    codeValue: 2
    enLabel: Firmware
    zhLabel: 固件
  - code: sdkType
    codeValue: 3
    enLabel: Kernel
    zhLabel: 内核
upLinkNetwork:
  - code: upLinkNetwork
    codeValue: 1
    enLabel: 2G
    zhLabel: 2G
  - code: upLinkNetwork
    codeValue: 2
    enLabel: 3G
    zhLabel: 3G
  - code: upLinkNetwork
    codeValue: 3
    enLabel: 4G
    zhLabel: 4G
  - code: upLinkNetwork
    codeValue: 4
    enLabel: Wi-Fi
    zhLabel: Wi-Fi
  - code: upLinkNetwork
    codeValue: 5
    enLabel: NB-IoT
    zhLabel: NB-IoT
  - code: upLinkNetwork
    codeValue: 6
    enLabel: BlueTooth
    zhLabel: BlueTooth
  - code: upLinkNetwork
    codeValue: 7
    enLabel: Wired
    zhLabel: 有线
fcntCheck:
  - code: fcntCheck
    codeValue: 0
    enLabel: Strict 16-bit
    zhLabel: Strict 16-bit
  - code: fcntCheck
    codeValue: 1
    enLabel: Strict 32-bit
    zhLabel: Strict 32-bit
  - code: fcntCheck
    codeValue: 2
    enLabel: Reset on zero
    zhLabel: Reset on zero
  - code: fcntCheck
    codeValue: 3
    enLabel: Disabled
    zhLabel: Disabled
region:
  - code: region
    codeValue:
    codeStringValue: EU863-870
    enLabel: EU 863-870MHz
    zhLabel: EU 863-870MHz
  - code: region
    codeValue:
    codeStringValue: US902-928
    enLabel: US 902-928MHz
    zhLabel: US 902-928MHz
  - code: region
    codeValue:
    codeStringValue: US902-928-PR
    enLabel: US 902-928MHz (Private)
    zhLabel: US 902-928MHz (Private)
  - code: region
    codeValue:
    codeStringValue: CN779-787
    enLabel: China 779-787MHz
    zhLabel: China 779-787MHz
  - code: region
    codeValue:
    codeStringValue: EU433
    enLabel: EU 433MHz
    zhLabel: EU 433MHz
  - code: region
    codeValue:
    codeStringValue: AU915-928
    enLabel: Australia 915-928MHz
    zhLabel: Australia 915-928MHz
  - code: region
    codeValue:
    codeStringValue: CN470-510
    enLabel: China 470-510MHz
    zhLabel: China 470-510MHz
  - code: region
    codeValue:
    codeStringValue: KR920-923
    enLabel: South Korea 920-923MHz
    zhLabel: South Korea 920-923MHz


# Product
productType:
  - code: productType
    codeValue: 1
    enLabel: Device
    zhLabel: 设备
  - code: productType
    codeValue: 2
    enLabel: Gateway
    zhLabel: 网关
gatewayProtocol:
  - code: gatewayProtocol
    codeValue: 1
    enLabel: MQTT
    zhLabel: MQTT
  - code: gatewayProtocol
    codeValue: 2
    enLabel: CoAP
    zhLabel: CoAP
  - code: gatewayProtocol
    codeValue: 3
    enLabel: LwM2M
    zhLabel: LwM2M
  - code: gatewayProtocol
    codeValue: 4
    enLabel: LoRa
    zhLabel: LoRa
  - code: gatewayProtocol
    codeValue: 5
    enLabel: HTTP
    zhLabel: HTTP
  - code: gatewayProtocol
    codeValue: 6
    enLabel: WebSocket
    zhLabel: WebSocket
  - code: gatewayProtocol
    codeValue: 7
    enLabel: Modbus
    zhLabel: Modbus
cloudProtocol:
  - code: cloudProtocol
    codeValue: 1
    enLabel: MQTT
    zhLabel: MQTT
  - code: cloudProtocol
    codeValue: 2
    enLabel: CoAP
    zhLabel: CoAP
  - code: cloudProtocol
    codeValue: 3
    enLabel: LwM2M
    zhLabel: LwM2M
  - code: cloudProtocol
    codeValue: 4
    enLabel: LoRa
    zhLabel: LoRa
  - code: cloudProtocol
    codeValue: 5
    enLabel: HTTP
    zhLabel: HTTP
  - code: cloudProtocol
    codeValue: 6
    enLabel: WebSocket
    zhLabel: WebSocket
  - code: cloudProtocol
    codeValue: 7
    enLabel: Modbus
    zhLabel: Modbus
pointDataType:
  - code: pointDataType
    codeValue: 1
    enLabel: Number
    zhLabel: 数值
  - code: pointDataType
    codeValue: 2
    enLabel: String
    zhLabel: 字符串
  - code: pointDataType
    codeValue: 3
    enLabel: Boolean
    zhLabel: 布尔
  - code: pointDataType
    codeValue: 4
    enLabel: Datetime
    zhLabel: 时间
  - code: pointDataType
    codeValue: 5
    enLabel: Location
    zhLabel: 地理位置
dataTransType:
  - code: dataTransType
    codeValue: 1
    enLabel: Up
    zhLabel: 只上报
  - code: dataTransType
    codeValue: 2
    enLabel: Down
    zhLabel: 只下发
  - code: dataTransType
    codeValue: 3
    enLabel: Up and Down
    zhLabel: 可上报可下发
streamType:
  - code: streamType
    codeValue: 1
    enLabel: Device Up
    zhLabel: 设备数据上报
  - code: streamType
    codeValue: 2
    enLabel: Device Down
    zhLabel: 设备数据下发
streamDataType:
  - code: streamDataType
    codeValue: 1
    enLabel: JSON
    zhLabel: JSON
  - code: streamDataType
    codeValue: 2
    enLabel: Binary
    zhLabel: 二进制
locationType:
  - code: locationType
    codeValue: 1
    enLabel: Longitude
    zhLabel: 经度
  - code: locationType
    codeValue: 2
    enLabel: Latitude
    zhLabel: 纬度
  - code: locationType
    codeValue: 3
    enLabel: Altitude
    zhLabel: 海拔


# Publish
publishStatus:
  - code: publishStatus
    codeValue: 0
    enLabel: Publish Failed
    zhLabel: 下发失败
  - code: publishStatus
    codeValue: 1
    enLabel: Published
    zhLabel: 已下发
  - code: publishStatus
    codeValue: 2
    enLabel: Publish Arrived
    zhLabel: 已到达
  - code: publishStatus
    codeValue: 3
    enLabel: Timed Publish
    zhLabel: 定时下发
  - code: publishStatus
    codeValue: 4
    enLabel: Operate Success
    zhLabel: 操作成功
  - code: publishStatus
    codeValue: 5
    enLabel: Operate Failed
    zhLabel: 操作失败
timerType:
  - code: timerType
    codeValue: 1
    enLabel: Fixed Timer
    zhLabel: 固定定时
  - code: timerType
    codeValue: 2
    enLabel: Interval Timer
    zhLabel: 间隔定时


# Task
taskType:
  - code: taskType
    codeValue: 1
    enLabel: Async Task
    zhLabel: 异步任务
  - code: taskType
    codeValue: 2
    enLabel: Timed Task
    zhLabel: 定时任务
taskStatus:
  - code: taskStatus
    codeValue: 1
    enLabel: Waiting
    zhLabel: 等待中
  - code: taskStatus
    codeValue: 2
    enLabel: Executing
    zhLabel: 执行中
  - code: taskStatus
    codeValue: 3
    enLabel: Success
    zhLabel: 成功
  - code: taskStatus
    codeValue: 4
    enLabel: Failed
    zhLabel: 失败
  - code: taskStatus
    codeValue: 5
    enLabel: Retry
    zhLabel: 重试


# Rule
ruleType:
  - code: ruleType
    codeValue: 1
    enLabel: Business Rule
    zhLabel: 业务规则
  - code: ruleType
    codeValue: 2
    enLabel: Scope Rule
    zhLabel: 围栏规则
actionType:
  - code: actionType
    codeValue: 1
    enLabel: Alert
    zhLabel: 告警
  - code: actionType
    codeValue: 2
    enLabel: Mail
    zhLabel: 邮件
  - code: actionType
    codeValue: 3
    enLabel: Webhook
    zhLabel: Webhook
  - code: actionType
    codeValue: 4
    enLabel: Publish
    zhLabel: 指令下发
  - code: actionType
    codeValue: 5
    enLabel: MQTT
    zhLabel: MQTT消息转发
chargeType:
  - code: chargeType
    codeValue: 1
    enLabel: Free
    zhLabel: 免费
  - code: chargeType
    codeValue: 2
    enLabel: Time
    zhLabel: 时长
  - code: chargeType
    codeValue: 3
    enLabel: Times
    zhLabel: 次数
  - code: chargeType
    codeValue: 4
    enLabel: Amount
    zhLabel: 条数
alertSeverity:
  - code: alertSeverity
    codeValue: 1
    enLabel: Urgent
    zhLabel: 紧急
  - code: alertSeverity
    codeValue: 2
    enLabel: Primary
    zhLabel: 主要
  - code: alertSeverity
    codeValue: 3
    enLabel: Secondary
    zhLabel: 次要
  - code: alertSeverity
    codeValue: 4
    enLabel: Warning
    zhLabel: 警告
messageType:
  - code: messageType
    codeValue: 1
    enLabel: Finance
    zhLabel: 财务消息
  - code: messageType
    codeValue: 2
    enLabel: Product
    zhLabel: 产品消息
  - code: messageType
    codeValue: 3
    enLabel: Security
    zhLabel: 安全消息
  - code: messageType
    codeValue: 4
    enLabel: Other
    zhLabel: 其它消息
  - code: messageType
    codeValue: 5
    enLabel: Announcement
    zhLabel: 公告
webhookType:
  - code: webhookType
    codeValue: 1
    enLabel: Private
    zhLabel: 私有
  - code: webhookType
    codeValue: 2
    enLabel: APICloud
    zhLabel: APICloud
  - code: webhookType
    codeValue: 3
    enLabel: LeanCloud
    zhLabel: LeanCloud
carrier:
  - code: carrier
    codeValue: 1
    enLabel: China Telecom
    zhLabel: 中国电信
  - code: carrier
    codeValue: 2
    enLabel: China Mobile
    zhLabel: 中国移动
  - code: carrier
    codeValue: 3
    enLabel: China Unicom
    zhLabel: 中国联通
  - code: carrier
    codeValue: 4
    enLabel: Other
    zhLabel: 其它
scopeType:
  - code: scopeType
    codeValue: 1
    enLabel: Active Area
    zhLabel: 活动区域
  - code: scopeType
    codeValue: 2
    enLabel: Forbidden Area
    zhLabel: 禁止区域
codeStatus:
  - code: codeStatus
    codeValue: 1
    enLabel: Review Pending
    zhLabel: 待审核
  - code: codeStatus
    codeValue: 2
    enLabel: Review Success
    zhLabel: 审核成功
  - code: codeStatus
    codeValue: 3
    enLabel: Review Failed
    zhLabel: 审核失败
dataType:
  - code: dataType
    codeValue: 1
    enLabel: event
    zhLabel: event
  - code: dataType
    codeValue: 2
    enLabel: response
    zhLabel: response


# Finance
topUpType:
  - code: topUpType
    codeValue: 1
    enLabel: Alipay
    zhLabel: 支付宝
  - code: topUpType
    codeValue: 2
    enLabel: Wechat Pay
    zhLabel: 微信支付
topUpStatus:
  - code: topUpStatus
    codeValue: 0
    enLabel: Top Up Failed
    zhLabel: 充值失败
  - code: topUpStatus
    enLabel: Top Up Pending
    zhLabel: 充值等待
    codeValue: 1
  - code: topUpStatus
    codeValue: 2
    enLabel: Top Up Success
    zhLabel: 充值完成
feeType:
  - code: feeType
    codeValue: 1
    enLabel: Top Up
    zhLabel: 充值
  - code: feeType
    codeValue: 2
    enLabel: Expense
    zhLabel: 消费
invoiceType:
  - code: invoiceType
    codeValue: 1
    enLabel: Individual
    zhLabel: 个人增值税普通发票
  - code: invoiceType
    codeValue: 2
    enLabel: Enterprise
    zhLabel: 企业增值税普通发票
invoiceStatus:
  - code: invoiceStatus
    codeValue: 0
    enLabel: Review Pending
    zhLabel: 审核中
  - code: invoiceStatus
    codeValue: 1
    enLabel: Canceled
    zhLabel: 已取消
  - code: invoiceStatus
    codeValue: 2
    enLabel: Posted
    zhLabel: 已邮寄
  - code: invoiceStatus
    codeValue: 3
    enLabel: Review Failed
    zhLabel: 未过审


# Other
allow:
  - code: allow
    codeValue: 1
    enLabel: Allow
    zhLabel: 允许
  - code: allow
    codeValue: 0
    enLabel: Deny
    zhLabel: 拒绝
access:
  - code: access
    codeValue: 1
    enLabel: Publish
    zhLabel: 发布
  - code: access
    codeValue: 2
    enLabel: Subscribe
    zhLabel: 订阅
  - code: access
    codeValue: 3
    enLabel: Publish or Subscribe
    zhLabel: 发布或订阅


# Dashboard
chartType:
  - code: chartType
    codeValue: 1
    enLabel: Line Chart
    zhLabel: 折线图
  - code: chartType
    codeValue: 2
    enLabel: Histogram
    zhLabel: 柱状图