# dict code yml

tenantType:
  - code: tenantType
    codeLabel: "Individual user"
    codeValue: 1
  - code: tenantType
    codeLabel: "Business user"
    codeValue: 2
userAuthType:
  - code: userAuthType
    codeLabel: "Role"
    codeValue: 1
  - code: userAuthType
    codeLabel: "Role and group"
    codeValue: 2
authType:
  - code: authType
    codeLabel: Token
    codeValue: 1
  - code: authType
    codeLabel: Certificate
    codeValue: 2
connectStatus:
  - code: connectStatus
    codeLabel: "Offline"
    codeValue: 0
  - code: connectStatus
    codeLabel: "Online"
    codeValue: 1
  - code: connectStatus
    codeLabel: "Authenticate failed"
    codeValue: 2
deviceType:
  - code: deviceType
    codeLabel: "Terminal"
    codeValue: 1
  - code: deviceType
    codeLabel: "Smart phone"
    codeValue: 3
deviceBlocked:
  - code: deviceBlocked
    codeLabel: "Allowed"
    codeValue: 0
  - code: deviceBlocked
    codeLabel: "Not allowed"
    codeValue: 1
enable:
  - code: enable
    codeLabel: "Enable"
    codeValue: 1
  - code: enable
    codeLabel: "Disable"
    codeValue: 0
inviteStatus:
  - code: inviteStatus
    codeLabel: "Not joined"
    codeValue: 0
  - code: inviteStatus
    codeLabel: "Joined"
    codeValue: 1
isLogged:
  - code: isLogged
    codeLabel: "Failed"
    codeValue: 0
  - code: isLogged
    codeLabel: "Success"
    codeValue: 1
deviceStatus:
  - code: deviceStatus
    codeLabel: "Offline"
    codeValue: 0
  - code: deviceStatus
    codeLabel: "Online"
    codeValue: 1
  - code: deviceStatus
    codeLabel: "Sleep"
    codeValue: 2
publishStatus:
  - code: publishStatus
    codeLabel: "Publish failed"
    codeValue: 0
  - code: publishStatus
    codeLabel: "Published"
    codeValue: 1
  - code: publishStatus
    codeLabel: "Publish arrived"
    codeValue: 2
  - code: publishStatus
    codeLabel: "Timed publish"
    codeValue: 3
  - code: publishStatus
    codeLabel: "Operate success"
    codeValue: 4
  - code: publishStatus
    codeLabel: "Operate failed"
    codeValue: 5
appStatus:
  - code: appStatus
    codeLabel: "Disable"
    codeValue: 0
  - code: appStatus
    codeLabel: "Enable"
    codeValue: 1
access:
  - code: access
    codeLabel: "Publish"
    codeValue: 1
  - code: access
    codeLabel: "Subscribe"
    codeValue: 2
  - code: access
    codeLabel: "Publish or subscribe"
    codeValue: 3
allow:
  - code: allow
    codeLabel: "Deny"
    codeValue: 0
  - code: allow
    codeLabel: "Allow"
    codeValue: 1
certEnable:
  - code: certEnable
    codeLabel: "Disable"
    codeValue: 0
  - code: certEnable
    codeLabel: "Enable"
    codeValue: 1

msgType:
  - code: msgType
    codeLabel: "login"
    codeValue: 1
  - code: msgType
    codeLabel: "subscribe"
    codeValue: 2
  - code: msgType
    codeLabel: "unsubscribe"
    codeValue: 3
  - code: msgType
    codeLabel: "publish"
    codeValue: 4
  - code: msgType
    codeLabel: "receive"
    codeValue: 5
autoCreateCert:
  - code: autoCreateCert
    codeLabel: "False"
    codeValue: 0
  - code:  autoCreateCert
    codeLabel: "True"
    codeValue: 1

pointDataType:
  - code: pointDataType
    codeLabel: "Number"
    codeValue: 1
  - code: pointDataType
    codeLabel: "String"
    codeValue: 3
  #- code: pointDataType
  #  codeLabel: "Fault"
  #  codeValue: 4
  - code: pointDataType
    codeLabel: "Bool"
    codeValue: 5
  - code: pointDataType
    codeLabel: "Location"
    codeValue: 6


locationType:
  - code: locationType
    codeValue: 1
    codeLabel: "Longitude"
  - code: locationType
    codeValue: 2
    codeLabel: "Latitude"
  - code: locationType
    codeValue: 3
    codeLabel: "Altitude"


dataTransType:
  - code: dataTransType
    codeLabel: "Up"
    codeValue: 1
  - code: dataTransType
    codeLabel: "Down"
    codeValue: 2
  - code: dataTransType
    codeLabel: "Up and down"
    codeValue: 3
streamType:
  - code: streamType
    codeLabel: "Device up"
    codeValue: 1
  - code: streamType
    codeLabel: "Device down"
    codeValue: 2
  - code: streamType
    codeLabel: "Gateway up"
    codeValue: 3
  - code: streamType
    codeLabel: "Gateway down"
    codeValue: 4

streamDataType:
  - code: streamDataType
    codeLabel: "JSON"
    codeValue: 1
  - code: streamDataType
    codeLabel: "Binary"
    codeValue: 2

topUpType:
  - code: topUpType
    codeLabel: "Alipay"
    codeValue: 1
  - code: topUpType
    codeLabel: "Wechat Pay"
    codeValue: 2
topUpStatus:
  - code: topUpStatus
    codeLabel: "Top up failed"
    codeValue: 0
  - code: topUpStatus
    codeLabel: "Top up pending"
    codeValue: 1
  - code: topUpStatus
    codeLabel: "Top up success"
    codeValue: 2

feeType:
  - code: feeType
    codeLabel: "Top up"
    codeValue: 1
  - code: feeType
    codeLabel: "Expense"
    codeValue: 2

invoiceType:
  - code: invoiceType
    codeLabel: "Individual"
    codeValue: 1
  - code: invoiceType
    codeLabel: "Enterprise"
    codeValue: 2

invoiceStatus:
  - code: invoiceStatus
    codeLabel: "Review pending"
    codeValue: 0
  - code: invoiceStatus
    codeLabel: "Canceled"
    codeValue: 1
  - code: invoiceStatus
    codeLabel: "Posted"
    codeValue: 2
  - code: invoiceStatus
    codeLabel: "Review failed"
    codeValue: 3


ruleType:
  - code: ruleType
    codeLabel: "Webhook"
    codeValue: 1

actionType:
  - code: actionType
    codeLabel: "Alert"
    codeValue: 1
  - code: actionType
    codeLabel: "Mail"
    codeValue: 2
  - code: actionType
    codeLabel: "Webhook"
    codeValue: 3
  - code: actionType
    codeLabel: "Publish"
    codeValue: 4

chargeType:
  - code: chargeType
    codeLabel: "Free"
    codeValue: 1
  - code: chargeType
    codeLabel: "Time"
    codeValue: 2
  - code: chargeType
    codeLabel: "Times"
    codeValue: 3
  - code: chargeType
    codeLabel: "Amount"
    codeValue: 4

serviceGroup:
  - code: serviceGroup
    codeLabel: "Base"
    codeValue: 1
  - code: serviceGroup
    codeLabel: "DMP"
    codeValue: 2
  - code: serviceGroup
    codeLabel: "AEP"
    codeValue: 3
  - code: serviceGroup
    codeLabel: "Value-added"
    codeValue: 4

alertSeverity:
  - code: alertSeverity
    codeLabel: "Urgent"
    codeValue: 1
  - code: alertSeverity
    codeLabel: "Primary"
    codeValue: 2
  - code: alertSeverity
    codeLabel: "Secondary"
    codeValue: 3
  - code: alertSeverity
    codeLabel: "Warning"
    codeValue: 4

messageType:
  - code: messageType
    codeLabel: "Finance"
    codeValue: 1
  - code: messageType
    codeLabel: "Product"
    codeValue: 2
  - code: messageType
    codeLabel: "Security"
    codeValue: 3
  - code: messageType
    codeLabel: "Other"
    codeValue: 4
  - code: messageType
    codeLabel: "Announcement"
    codeValue: 5

sdkType:
  - code: sdkType
    codeLabel: "Application"
    codeValue: 1
  - code: sdkType
    codeLabel: "Firmware"
    codeValue: 2
  - code: sdkType
    codeLabel: "Kernel"
    codeValue: 3

controlType:
  - code: controlType
    codeValue: 1
    codeLabel: "Publish"
  - code: controlType
    codeValue: 2
    codeLabel: "Read"
  - code: controlType
    codeValue: 3
    codeLabel: "Write"
  - code: controlType
    codeValue: 4
    codeLabel: "Execute"


publishType:
  - code: publishType
    codeValue: 1
    codeLabel: "Device publish"
  - code: publishType
    codeValue: 2
    codeLabel: "Group publish"

timerType:
  - code: timerType
    codeValue: 1
    codeLabel: 'Fixed timer'
  - code: timerType
    codeValue: 2
    codeLabel: 'Interval timer'
metricType:
  - code: metricType
    codeValue: 1
    codeLabel: Formula metric
  - code: metricType
    codeValue: 2
    codeLabel: Aggregate metric
  - code: metricType
    codeValue: 3
    codeLabel: Original metric
aggregateData:
  - code: aggregateData
    codeValue: 1
    codeLabel: Formula value
  - code: aggregateData
    codeValue: 2
    codeLabel: Original value
aggregateType:
  - code: aggregateType
    codeValue: 1
    codeLabel: "Max"
  - code: aggregateType
    codeValue: 2
    codeLabel: "Min"
  - code: aggregateType
    codeValue: 3
    codeLabel: "Average"
  - code: aggregateType
    codeValue: 4
    codeLabel: "Sum"
chartType:
  - code: chartType
    codeValue: 1
    codeLabel: Line chart
  - code: chartType
    codeValue: 2
    codeLabel: Histogram


upLinkSystem:
  - code: upLinkSystem
    codeValue: 1
    codeLabel: Cloud
  - code: upLinkSystem
    codeValue: 2
    codeLabel: Gateway
  - code: upLinkSystem
    codeValue: 3
    codeLabel: Device

cloudProtocol:
  - code: cloudProtocol
    codeValue: 1
    codeLabel: MQTT
  - code: cloudProtocol
    codeValue: 2
    codeLabel: CoAP
  - code: cloudProtocol
    codeValue: 3
    codeLabel: LwM2M
  - code: cloudProtocol
    codeValue: 4
    codeLabel: LoRa
  - code: cloudProtocol
    codeValue: 5
    codeLabel: HTTP
  - code: cloudProtocol
    codeValue: 6
    codeLabel: WebSocket
  - code: cloudProtocol
    codeValue: 7
    codeLabel: Modbus

webhookType:
  - code: webhookType
    codeValue: 1
    codeLabel: Private
  - code: webhookType
    codeValue: 2
    codeLabel: APICloud
  - code: webhookType
    codeValue: 3
    codeLabel: LeanCloud

carrier:
  - code: carrier
    codeValue: 1
    codeLabel: China Telecom
  - code: carrier
    codeValue: 2
    codeLabel: China Mobile
  - code: carrier
    codeValue: 3
    codeLabel: China Unicom
  - code: carrier
    codeValue: 4
    codeLabel: Other

physicalNetwork:
  - code: physicalNetwork
    codeValue: 1
    codeLabel: Wi-Fi
  - code: physicalNetwork
    codeValue: 2
    codeLabel: 2G
  - code: physicalNetwork
    codeValue: 3
    codeLabel: 3G
  - code: physicalNetwork
    codeValue: 4
    codeLabel: 4G
  - code: physicalNetwork
    codeValue: 5
    codeLabel: NB-IoT
  - code: physicalNetwork
    codeValue: 6
    codeLabel: BlueTooth

scopeType:
  - code: scopeType
    codeValue: 1
    codeLabel: Active area
  - code: scopeType
    codeValue: 2
    codeLabel: Forbidden area

productResource:
  - code: productResource
    codeValue:
    codeStringValue: serialNumber
    codeLabel: Serial number
  - code: productResource
    codeValue:
    codeStringValue: softVersion
    codeLabel: Soft version
  - code: productResource
    codeValue:
    codeStringValue: hardwareVersion
    codeLabel: Hardware version
  - code: productResource
    codeValue:
    codeStringValue: manufacturer
    codeLabel: Manufacturer

templateType:
  - code: templateType
    codeValue: 1
    codeLabel: Switch
  - code: templateType
    codeValue: 2
    codeLabel:  Enum
  - code: templateType
    codeValue: 3
    codeLabel: Number
  - code: templateType
    codeValue: 4
    codeLabel: String
  - code: templateType
    codeValue: 5
    codeLabel: Bool
  - code: templateType
    codeValue: 6
    codeLabel: Time

fcntCheck:
  - code: fcntCheck
    codeValue: 0
    codeLabel: Strict 16-bit
  - code: fcntCheck
    codeValue: 1
    codeLabel: Strict 32-bit
  - code: fcntCheck
    codeValue: 2
    codeLabel: Reset on zero
  - code: fcntCheck
    codeValue: 3
    codeLabel: Disabled


region:
  - code: region
    codeValue:
    codeStringValue: EU863-870
    codeLabel: EU 863-870MHz
  - code: region
    codeValue:
    codeStringValue: US902-928
    codeLabel: US 902-928MHz
  - code: region
    codeValue:
    codeStringValue: US902-928-PR
    codeLabel: US 902-928MHz (Private)
  - code: region
    codeValue:
    codeStringValue: CN779-787
    codeLabel: China 779-787MHz
  - code: region
    codeValue:
    codeStringValue: EU433
    codeLabel: EU 433MHz
  - code: region
    codeValue:
    codeStringValue: AU915-928
    codeLabel: Australia 915-928MHz
  - code: region
    codeValue:
    codeStringValue: CN470-510
    codeLabel: China 470-510MHz
  - code: region
    codeValue:
    codeStringValue: KR920-923
    codeLabel: South Korea 920-923MHz

gatewayProtocol:
  - code: gatewayProtocol
    codeValue: 1
    codeLabel: MQTT
  - code: gatewayProtocol
    codeValue: 2
    codeLabel: CoAP
  - code: gatewayProtocol
    codeValue: 3
    codeLabel: LwM2M
  - code: gatewayProtocol
    codeValue: 4
    codeLabel: LoRa
  - code: gatewayProtocol
    codeValue: 5
    codeLabel: HTTP
  - code: gatewayProtocol
    codeValue: 6
    codeLabel: WebSocket
  - code: gatewayProtocol
    codeValue: 7
    codeLabel: Modbus

upLinkNetwork:
  - code: upLinkNetwork
    codeValue: 1
    codeLabel: 2G
  - code: upLinkNetwork
    codeValue: 2
    codeLabel: 3G
  - code: upLinkNetwork
    codeValue: 3
    codeLabel: 4G
  - code: upLinkNetwork
    codeValue: 4
    codeLabel: Wi-Fi
  - code: upLinkNetwork
    codeValue: 5
    codeLabel: NB-IoT

productType:
  - code: productType
    codeValue: 1
    codeLabel: Device
  - code: productType
    codeValue: 2
    codeLabel: Gateway

taskType:
  - code: taskType
    codeValue: 1
    codeLabel: Async task
  - code: taskType
    codeValue: 2
    codeLabel: Timed task


taskStatus:
  - code: taskStatus
    codeValue: 1
    codeLabel: Waiting
  - code: taskStatus
    codeValue: 2
    codeLabel: Executing
  - code: taskStatus
    codeValue: 3
    codeLabel: Success
  - code: taskStatus
    codeValue: 4
    codeLabel: Failed
  - code: taskStatus
    codeValue: 5
    codeLabel: Retry

codeStatus:
  - code: codeStatus
    codeValue: 1
    codeLabel: Review pending
  - code: codeStatus
    codeValue: 2
    codeLabel: Review success
  - code: codeStatus
    codeValue: 3
    codeLabel: Review failed